@baseUrl = http://localhost:3000/items
@json = application/json

############################################
### 🔹 LISTAR TODOS OS ITENS
GET {{baseUrl}}
Accept: {{json}}

############################################
### 🔹 BUSCAR ITEM POR ID
GET {{baseUrl}}/2
Accept: {{json}}

############################################
### 🔹 CRIAR NOVO ITEM
POST {{baseUrl}}
Content-Type: {{json}}

{
  "nome": "Chocolate",
  "descricao": "cambúrguer 180g com queijo e bacon",
  "preco": 29.90,
  "id_categoria": 4
}

############################################
### 🔹 ATUALIZAR ITEM (NOME E PREÇO)
PUT {{baseUrl}}/13
Content-Type: {{json}}

{
  "nome": "Wwambúrguer Artesanal Ddao",
  "preco": 34.90
}

############################################
### 🔹 ATUALIZAR ITEM (DESCRIÇÃO)
PUT {{baseUrl}}/7
Content-Type: {{json}}

{
  "descricao": "hambúrguer duplo 180g com queijo cheddar"
}

############################################
### 🔹 ATUALIZAR ITEM (CATEGORIA)
PUT {{baseUrl}}/2
Content-Type: {{json}}

{
  "id_categoria": 2
}

############################################
### 🔹 DELETAR ITEM
DELETE {{baseUrl}}/12
Accept: {{json}}
