@baseUrl = http://localhost:3000
@orderId = 1
@itemOrderId = 1

##################################################
# 1️⃣ Listar itens de um pedido
##################################################

GET {{baseUrl}}/item-orders/order/{{orderId}}
Content-Type: application/json


##################################################
# 2️⃣ Criar item no pedido
##################################################

POST {{baseUrl}}/item-orders/order/{{orderId}}
Content-Type: application/json

{
  "id_item": 1,
  "quantidade": 3
}


##################################################
# 3️⃣ Atualizar item do pedido
##################################################

PUT {{baseUrl}}/item-orders/{{itemOrderId}}
Content-Type: application/json

{
  "quantidade": 5
}


##################################################
# 4️⃣ Deletar item do pedido
##################################################

DELETE {{baseUrl}}/item-orders/{{itemOrderId}}
Content-Type: application/json