@baseUrl = http://localhost:3000/items
@json = application/json

############################################
### 🔹 LISTAR TODOS OS ITENS
GET {{baseUrl}}
Accept: {{json}}

############################################
### 🔹 BUSCAR ITEM POR ID
GET {{baseUrl}}/2
Accept: {{json}}

############################################
### 🔹 CRIAR NOVO ITEM
POST {{baseUrl}}
Content-Type: {{json}}

{
  "nome": "Chocolate Branco",
  "descricao": "Chocolate Branco",
  "preco": 15.00,
  "id_categoria": 1
}

############################################
### 🔹 ATUALIZAR ITEM (DESCRIÇÃO)
PUT {{baseUrl}}/1
Content-Type: {{json}}

{
  "preco": 15.00
}

############################################
### 🔹 ATUALIZAR ITEM (CATEGORIA)
PUT {{baseUrl}}/2
Content-Type: {{json}}

{
  "id_categoria": 2
}

############################################
### 🔹 DELETAR ITEM
DELETE {{baseUrl}}/12
Accept: {{json}}
