@baseUrl = http://localhost:3000
@json = application/json

### Criar administrador - POST /admins
POST {{baseUrl}}/admins
Content-Type: {{json}}

{
  "nome": "Itaa",
  "email": "ita@yahoo.com",
  "senha": "123456"
}

### Listar administradores - GET /admins
GET {{baseUrl}}/admins
Accept: application/json

### Listar administradores - GET /admins/:id
GET {{baseUrl}}/admins/1
Accept: application/json

### Tentar criar com email duplicado (deve retornar erro 400)
POST {{baseUrl}}/admins
Content-Type: {{json}}

{
  "nome": "Test Admin Duplicate",
  "email": "ita@yahoo.com",
  "senha": "Password123!"
}

### Atualizar administrador - PUT /admins/:id
PUT {{baseUrl}}/admins/1
Content-Type: {{json}}

{
  "nome": "Updated Test Admin",
  "email": "updatedtestadmin@example.com"
}

### Deletar administrador - DELETE /admins/:id
DELETE {{baseUrl}}/admins/2