###
# Listar todos os endereços
GET http://localhost:3000/addresses
Accept: application/json

###
# Buscar um endereço pelo ID
GET http://localhost:3000/addresses/1
Accept: application/json

###
# Criar um novo endereço (válido)
POST http://localhost:3000/addresses
Content-Type: application/json

{
  "rua": "Rua Exemplo",
  "numero": 123,
  "bairro": "Centro",
  "cidade": "Cidade Teste",
  "estado": "SP",
  "cep": "12345-678",
  "id_cliente": 2
}

###
# Criar um novo endereço (erro: número negativo)
POST http://localhost:3000/addresses
Content-Type: application/json

{
  "rua": "222",
  "numero": 50,
  "bairro": "Bairro X",
  "cidade": "Cidade Y",
  "estado": "RJ",
  "cep": "98765-432",
  "id_cliente": 2
}

###
# Atualizar um endereço existente (válido)
PUT http://localhost:3000/addresses/1
Content-Type: application/json

{
  "rua": "Rua Alterada",
  "numero": 456,
  "bairro": "Bairro Novo"
}

###
# Atualizar endereço com erro (ID de cliente inválido)
PUT http://localhost:3000/addresses/2
Content-Type: application/json

{
  "id_cliente": 9999
}

###
# Deletar um endereço
DELETE http://localhost:3000/addresses/1
Accept: application/json

###
# Buscar um endereço inexistente (deve retornar erro ou null)
GET http://localhost:3000/addresses/999
Accept: application/json
